<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAFxeLNv\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAFxeLNv/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAFxeLNv.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAFxeLNv\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAFxeLNv\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AFxeLNv',
    'container.build_id' => 'b035a3a2',
    'container.build_time' => 1560444130,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAFxeLNv');
