
CREATE DATABASE IF NOT EXISTS AIMI;

USE AIMI;

-- DELETING
DROP TABLE IF EXISTS PRODUCTO_TALLA;
DROP TABLE IF EXISTS PRODUCTO;
DROP TABLE IF EXISTS TALLA;
DROP TABLE IF EXISTS GENERO;
DROP TABLE IF EXISTS CATEGORIA;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS COMERCIAL;



-- CREATING TABLES

CREATE TABLE PRODUCTO (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  CODIGO_BARRA BIGINT NOT NULL,
  CODIGO_PRODUCTO VARCHAR(30),
  DESCRIPCION TEXT,
  PRECIO_COMPRA DECIMAL(6,2),
  PVP DECIMAL(6,2),
  CANTIDAD_PACK INTEGER,
  STOCK INTEGER,
  AVISO_STOCK INTEGER,
  photo_path VARCHAR(255) DEFAULT '',
  config TEXT,
  created_at DATETIME DEFAULT NOW(),
  updated_at DATETIME DEFAULT NOW(),
  ID_GENERO INTEGER,
  ID_CATEGORIA INTEGER
);



CREATE TABLE TALLA (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  TEXTO VARCHAR(255),
  config TEXT,
  created_at DATETIME DEFAULT NOW(),
  updated_at DATETIME DEFAULT NOW()
);

CREATE TABLE PRODUCTO_TALLA (
  ID_PRODUCTO INTEGER,
  ID_TALLA INTEGER,
  PRIMARY KEY (ID_TALLA, ID_PRODUCTO)
);

CREATE TABLE GENERO (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  TEXTO VARCHAR(255),
  config TEXT,
  created_at DATETIME DEFAULT NOW(),
  updated_at DATETIME DEFAULT NOW()
);

CREATE TABLE CATEGORIA (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  TEXTO VARCHAR(255),
  config TEXT,
  created_at DATETIME DEFAULT NOW(),
  updated_at DATETIME DEFAULT NOW()
);

CREATE TABLE CLIENTE (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  CODIGO_CLIENTE varchar(255) NOT NULL,
  NOMBRE_CLIENTE VARCHAR(255) DEFAULT NULL,
  NOMBRE_CONTACTO VARCHAR(255) DEFAULT NULL,
  TELEFONO_CONTACTO INT(11) DEFAULT NULL,
  CIF_DNI_NIE VARCHAR(255) NOT NULL,
  DIRECCION VARCHAR(255) DEFAULT NULL,
  CP VARCHAR(11) DEFAULT NULL,
  CIUDAD VARCHAR(255) DEFAULT NULL,
  PROVINCIA VARCHAR(255) DEFAULT NULL,
  PAIS VARCHAR(255) DEFAULT NULL,
  TELEFONO1 INT(11) DEFAULT NULL,
  TELEFONO2 INT(11) DEFAULT NULL,
  MOVIL INT(11) DEFAULT NULL,
  FAX VARCHAR(255) DEFAULT NULL,
  EMAIL VARCHAR(255) DEFAULT NULL,
  DIRECCION_ENVIO VARCHAR(255) DEFAULT NULL,
  CP_ENVIO VARCHAR(255) DEFAULT NULL,
  CIUDAD_ENVIO VARCHAR(255) DEFAULT NULL,
  PROVINCIA_ENVIO VARCHAR(255) DEFAULT NULL,
  PAIS_ENVIO VARCHAR(255) DEFAULT NULL,
  DESCUENTO_CLIENTE INT(11) DEFAULT NULL,
  config TEXT,
  created_at DATETIME DEFAULT NOW(),
  updated_at DATETIME DEFAULT NOW()
);

CREATE TABLE COMERCIAL (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  CODIGO_COMERCIO VARCHAR(255) NOT NULL,
  NOMBRE_COMERCIAL VARCHAR(255) NOT NULL,
  TELEFONO_COMERCIAL INT(11) NOT NULL,
  config TEXT,
  created_at DATETIME DEFAULT NOW(),
  updated_at DATETIME DEFAULT NOW()
);




-- FK --

ALTER TABLE PRODUCTO ADD FOREIGN KEY (ID_GENERO) REFERENCES GENERO(ID) ON DELETE SET NULL;
ALTER TABLE PRODUCTO ADD FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID) ON DELETE SET NULL;
ALTER TABLE PRODUCTO_TALLA ADD FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID) ON DELETE CASCADE;
ALTER TABLE PRODUCTO_TALLA ADD FOREIGN KEY (ID_TALLA) REFERENCES TALLA(ID) ON DELETE CASCADE;

-- ALTER TABLE queues ADD FOREIGN KEY (id_store) REFERENCES stores(id) ON DELETE CASCADE;

