
CREATE DATABASE IF NOT EXISTS AIMI;

USE AIMI;

-- DELETING
DROP TABLE IF EXISTS PRODUCTO_TALLA;
DROP TABLE IF EXISTS PRODUCTO;
DROP TABLE IF EXISTS TALLA;
DROP TABLE IF EXISTS GENERO;
DROP TABLE IF EXISTS CATEGORIA;


-- CREATING TABLES

CREATE TABLE PRODUCTO (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  CODIGO_BARRA BIGINT NOT NULL,
  CODIGO_PRODUCTO VARCHAR(30),
  DESCRIPCION TEXT,
  PRECIO_COMPRA DECIMAL(6,2),
  PVP DECIMAL(6,2),
  CANTIDAD_PACK INTEGER,
  STOCK INTEGER,
  AVISO_STOCK INTEGER,
  photo_path VARCHAR(255) DEFAULT '',
  config TEXT,
  created_at DATETIME DEFAULT NOW(),
  updated_at DATETIME DEFAULT NOW(),
  ID_GENERO INTEGER,
  ID_CATEGORIA INTEGER
);



CREATE TABLE TALLA (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  TEXTO VARCHAR(255),
  config TEXT,
  created_at DATETIME DEFAULT NOW(),
  updated_at DATETIME DEFAULT NOW()
);

CREATE TABLE PRODUCTO_TALLA (
  ID_PRODUCTO INTEGER,
  ID_TALLA INTEGER,
  PRIMARY KEY (ID_TALLA, ID_PRODUCTO)
);

CREATE TABLE GENERO (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  TEXTO VARCHAR(255),
  config TEXT,
  created_at DATETIME DEFAULT NOW(),
  updated_at DATETIME DEFAULT NOW()
);

CREATE TABLE CATEGORIA (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  TEXTO VARCHAR(255),
  config TEXT,
  created_at DATETIME DEFAULT NOW(),
  updated_at DATETIME DEFAULT NOW()
);

-- FK --

ALTER TABLE PRODUCTO ADD FOREIGN KEY (ID_GENERO) REFERENCES GENERO(ID) ON DELETE SET NULL;
ALTER TABLE PRODUCTO ADD FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID) ON DELETE SET NULL;
ALTER TABLE PRODUCTO_TALLA ADD FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID) ON DELETE CASCADE;
ALTER TABLE PRODUCTO_TALLA ADD FOREIGN KEY (ID_TALLA) REFERENCES TALLA(ID) ON DELETE CASCADE;

-- ALTER TABLE queues ADD FOREIGN KEY (id_store) REFERENCES stores(id) ON DELETE CASCADE;

